### ISSUE TITLE
reshare

### ISSUE THREAD

**Issue by jonnychipz** [jwroper/scripts-public#1]
No issue whatsoever! But can you share your repos with me again bud...... you can remove my jonnychips account in favour of the Jonnychipz (with a z account) ;)

![image](https://user-images.githubusercontent.com/55880472/89700319-240bec80-d925-11ea-9d5c-91bdb252d6f0.jpeg)

**Comment by jwroper** [comment]
Hi jonnychipz - this one is public so you should be able to see the script in there already? Let me know if not?

**Comment by jonnychipz** [comment]
Yeah can see this one but didn't know if you were still maintaining the private repo's or if you had shifted them into Gitlab?

**Comment by jwroper** [comment]
hi, yeah all the BT stuff is in Gitlab now :) saying that i'm just about to put Joes code for the excel -> terraform convertor up and that will be public. Cheers
